// <auto-generated />
using System;
using Flipped_Classroom.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flipped_Classroom.Migrations
{
    [DbContext(typeof(Swp391NihongoContext))]
    [Migration("20260530045623_AddQuizPublishingFields")]
    partial class AddQuizPublishingFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flipped_Classroom.Models.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("NodeId")
                        .HasColumnType("int");

                    b.Property<string>("RequirementText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Assignme__3214EC07909120E8");

                    b.HasIndex("ClassId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("NodeId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("InviteCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("Id")
                        .HasName("PK__Classes__3214EC071D7703CC");

                    b.HasIndex("ManagerId");

                    b.HasIndex(new[] { "InviteCode" }, "UQ__Classes__B8659E393A96C081")
                        .IsUnique()
                        .HasFilter("[InviteCode] IS NOT NULL");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.ClassMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsSupportTeam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__ClassMem__3214EC07EB971E15");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "ClassId", "UserId" }, "UQ_Class_User")
                        .IsUnique();

                    b.ToTable("ClassMembers");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.ClassSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Room")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateOnly>("StudyDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassSchedule");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.FeedbackComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.Property<string>("TimelineStamp")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Feedback__3214EC07504212DA");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("Feedback_Comments", (string)null);
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GradedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("GradedBy")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Grades__3214EC0732B994D3");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.GradeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__GradeCat__3214EC076B3DA5A8");

                    b.HasIndex("ClassId");

                    b.ToTable("GradeCategories");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Groups__3214EC07F0DFEE88");

                    b.HasIndex("ClassId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__GroupMem__3214EC0739F6DEBA");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "GroupId", "StudentId" }, "UQ_Group_Student")
                        .IsUnique();

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Material__3214EC074BD3A5D7");

                    b.HasIndex("NodeId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Mileston__3214EC076EA52477");

                    b.HasIndex("ProjectId");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstimatedMinutes")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsReviewNode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("NodeOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("ParentNodeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Nodes__3214EC07510306F0");

                    b.HasIndex("ClassId");

                    b.HasIndex("ParentNodeId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Projects__3214EC07187C8DAE");

                    b.HasIndex("ClassId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.QaReply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("QaThreadId")
                        .HasColumnType("int")
                        .HasColumnName("QA_ThreadId");

                    b.Property<string>("ReplyText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__QA_Repli__3214EC07961B157A");

                    b.HasIndex("QaThreadId");

                    b.HasIndex("UserId");

                    b.ToTable("QA_Replies", (string)null);
                });

            modelBuilder.Entity("Flipped_Classroom.Models.QaThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("NodeId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("UpvoteCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__QA_Threa__3214EC0771C493A0");

                    b.HasIndex("ClassId");

                    b.HasIndex("NodeId");

                    b.HasIndex("StudentId");

                    b.ToTable("QA_Threads", (string)null);
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrectAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DifficultyLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsQuestionBank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Visibility")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Always");

                    b.HasKey("Id")
                        .HasName("PK__Question__3214EC07A73FBC5A");

                    b.HasIndex("NodeId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("OptionContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Question__3214EC07D659E11E");

                    b.HasIndex("QuestionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Quizzes__3214EC078FCFA5F4");

                    b.HasIndex("NodeId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.QuizQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal?>("Point")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(1m);

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__QuizQues__3214EC0744CD312F");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuizId");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.QuizResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__QuizResu__3214EC07E4777785");

                    b.HasIndex("QuizId");

                    b.HasIndex("StudentId");

                    b.ToTable("QuizResults");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.StudentMistake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ErrorCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("MistakeType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("NextReviewDate")
                        .HasColumnType("date");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudentM__3214EC0743102BE5");

                    b.HasIndex("QuestionId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentMistakes");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.StudentProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime");

                    b.Property<bool?>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__StudentP__3214EC072617F85C");

                    b.HasIndex("NodeId");

                    b.HasIndex(new[] { "StudentId", "NodeId" }, "UQ_Student_Node")
                        .IsUnique();

                    b.ToTable("StudentProgress", (string)null);
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("ContentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Submitted");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmitAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Submissi__3214EC077AE01F90");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("GroupId");

                    b.HasIndex("StudentId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC07D70BBCD3");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E47AD89E9C")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UX_Users_Email")
                        .IsUnique()
                        .HasFilter("([Email] IS NOT NULL)");

                    b.HasIndex(new[] { "GoogleId" }, "UX_Users_GoogleId")
                        .IsUnique()
                        .HasFilter("([GoogleId] IS NOT NULL)");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Assignment", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Class", "Class")
                        .WithMany("Assignments")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Assignment_Class");

                    b.HasOne("Flipped_Classroom.Models.User", "CreatedByNavigation")
                        .WithMany("Assignments")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Assignment_Teacher");

                    b.HasOne("Flipped_Classroom.Models.Node", "Node")
                        .WithMany("Assignments")
                        .HasForeignKey("NodeId")
                        .HasConstraintName("FK_Assignment_Node");

                    b.Navigation("Class");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Class", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.User", "Manager")
                        .WithMany("Classes")
                        .HasForeignKey("ManagerId")
                        .IsRequired()
                        .HasConstraintName("FK_Class_Manager");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.ClassMember", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Class", "Class")
                        .WithMany("ClassMembers")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Member_Class");

                    b.HasOne("Flipped_Classroom.Models.User", "User")
                        .WithMany("ClassMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Member_User");

                    b.Navigation("Class");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.ClassSchedule", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Class", "Class")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.FeedbackComment", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.User", "Reviewer")
                        .WithMany("FeedbackComments")
                        .HasForeignKey("ReviewerId")
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_Reviewer");

                    b.HasOne("Flipped_Classroom.Models.Submission", "Submission")
                        .WithMany("FeedbackComments")
                        .HasForeignKey("SubmissionId")
                        .IsRequired()
                        .HasConstraintName("FK_Feedback_Submission");

                    b.Navigation("Reviewer");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Grade", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.GradeCategory", "Category")
                        .WithMany("Grades")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Grade_Cat");

                    b.HasOne("Flipped_Classroom.Models.User", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Grade_Student");

                    b.Navigation("Category");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.GradeCategory", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Class", "Class")
                        .WithMany("GradeCategories")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_GradeCat_Class");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Group", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Class", "Class")
                        .WithMany("Groups")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Group_Class");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.GroupMember", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Group", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK_GroupMember_Group");

                    b.HasOne("Flipped_Classroom.Models.User", "Student")
                        .WithMany("GroupMembers")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_GroupMember_Student");

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Material", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Node", "Node")
                        .WithMany("Materials")
                        .HasForeignKey("NodeId")
                        .IsRequired()
                        .HasConstraintName("FK_Material_Node");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Milestone", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Project", "Project")
                        .WithMany("Milestones")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Milestone_Project");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Node", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Class", "Class")
                        .WithMany("Nodes")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Node_Class");

                    b.HasOne("Flipped_Classroom.Models.Node", "ParentNode")
                        .WithMany("InverseParentNode")
                        .HasForeignKey("ParentNodeId")
                        .HasConstraintName("FK_Node_Parent");

                    b.Navigation("Class");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Project", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Class", "Class")
                        .WithMany("Projects")
                        .HasForeignKey("ClassId")
                        .IsRequired()
                        .HasConstraintName("FK_Project_Class");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.QaReply", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.QaThread", "QaThread")
                        .WithMany("QaReplies")
                        .HasForeignKey("QaThreadId")
                        .IsRequired()
                        .HasConstraintName("FK_Reply_QA");

                    b.HasOne("Flipped_Classroom.Models.User", "User")
                        .WithMany("QaReplies")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Reply_User");

                    b.Navigation("QaThread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.QaThread", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Class", "Class")
                        .WithMany("QaThreads")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK_QA_Class");

                    b.HasOne("Flipped_Classroom.Models.Node", "Node")
                        .WithMany("QaThreads")
                        .HasForeignKey("NodeId")
                        .HasConstraintName("FK_QA_Node");

                    b.HasOne("Flipped_Classroom.Models.User", "Student")
                        .WithMany("QaThreads")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_QA_Student");

                    b.Navigation("Class");

                    b.Navigation("Node");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Question", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Node", "Node")
                        .WithMany("Questions")
                        .HasForeignKey("NodeId")
                        .IsRequired()
                        .HasConstraintName("FK_Question_Node");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.QuestionOption", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Question", "Question")
                        .WithMany("QuestionOptions")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_Option_Question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Quiz", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Node", "Node")
                        .WithMany("Quizzes")
                        .HasForeignKey("NodeId")
                        .IsRequired()
                        .HasConstraintName("FK_Quiz_Node");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.QuizQuestion", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Question", "Question")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_QQ_Question");

                    b.HasOne("Flipped_Classroom.Models.Quiz", "Quiz")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("QuizId")
                        .IsRequired()
                        .HasConstraintName("FK_QQ_Quiz");

                    b.Navigation("Question");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.QuizResult", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Quiz", "Quiz")
                        .WithMany("QuizResults")
                        .HasForeignKey("QuizId")
                        .IsRequired()
                        .HasConstraintName("FK_Result_Quiz");

                    b.HasOne("Flipped_Classroom.Models.User", "Student")
                        .WithMany("QuizResults")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Result_Student");

                    b.Navigation("Quiz");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.StudentMistake", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Question", "Question")
                        .WithMany("StudentMistakes")
                        .HasForeignKey("QuestionId")
                        .IsRequired()
                        .HasConstraintName("FK_Mistake_Question");

                    b.HasOne("Flipped_Classroom.Models.User", "Student")
                        .WithMany("StudentMistakes")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Mistake_Student");

                    b.Navigation("Question");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.StudentProgress", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Node", "Node")
                        .WithMany("StudentProgresses")
                        .HasForeignKey("NodeId")
                        .IsRequired()
                        .HasConstraintName("FK_Progress_Node");

                    b.HasOne("Flipped_Classroom.Models.User", "Student")
                        .WithMany("StudentProgresses")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Progress_Student");

                    b.Navigation("Node");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Submission", b =>
                {
                    b.HasOne("Flipped_Classroom.Models.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Submission_Assignment");

                    b.HasOne("Flipped_Classroom.Models.Group", "Group")
                        .WithMany("Submissions")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK_Submission_Group");

                    b.HasOne("Flipped_Classroom.Models.User", "Student")
                        .WithMany("Submissions")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Submission_Student");

                    b.Navigation("Assignment");

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Class", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ClassMembers");

                    b.Navigation("ClassSchedules");

                    b.Navigation("GradeCategories");

                    b.Navigation("Groups");

                    b.Navigation("Nodes");

                    b.Navigation("Projects");

                    b.Navigation("QaThreads");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.GradeCategory", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Group", b =>
                {
                    b.Navigation("GroupMembers");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Node", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("InverseParentNode");

                    b.Navigation("Materials");

                    b.Navigation("QaThreads");

                    b.Navigation("Questions");

                    b.Navigation("Quizzes");

                    b.Navigation("StudentProgresses");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Project", b =>
                {
                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.QaThread", b =>
                {
                    b.Navigation("QaReplies");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Question", b =>
                {
                    b.Navigation("QuestionOptions");

                    b.Navigation("QuizQuestions");

                    b.Navigation("StudentMistakes");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Quiz", b =>
                {
                    b.Navigation("QuizQuestions");

                    b.Navigation("QuizResults");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.Submission", b =>
                {
                    b.Navigation("FeedbackComments");
                });

            modelBuilder.Entity("Flipped_Classroom.Models.User", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ClassMembers");

                    b.Navigation("Classes");

                    b.Navigation("FeedbackComments");

                    b.Navigation("Grades");

                    b.Navigation("GroupMembers");

                    b.Navigation("QaReplies");

                    b.Navigation("QaThreads");

                    b.Navigation("QuizResults");

                    b.Navigation("StudentMistakes");

                    b.Navigation("StudentProgresses");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
